### PR TITLE
Do not try to resize popup windows

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by idbrii** [comment]
Could you give an example of how to trigger the bug this is fixing?

**Comment by gotcha** [comment]
I installed https://github.com/voldikss/vim-floaterm

Running `:FloatermNew` or `:FloatermToggle` systematically triggers the following:

```
Autocommands for "*"..function <SNR>52_resize_to_golden_ratio[27]..<SNR>52_resize_ignored_windows:
line    4:
E994: Not allowed in a popup window
line    7:
line    4:
E994: Not allowed in a popup window
line    7:
```

**Comment by idbrii** [comment]
Sorry for the delay. I can reproduce the issue and your solution looks great!

**Comment by gotcha** [comment]
Thanks !

PS: No need to be sorry, as an OS maintainer, I like to be nudged. Hope this was gentle enough.

**Pull request merged**
